### ISSUE TITLE
Get posts by tag - Endpoint changed?

### ISSUE THREAD

**Issue by andor99** [Taz03/JIA#31]
Hello, I wanted to ask if you know the endpoint of getting the posts by providing a tag. I believe they recently changed it because it used to work with `https://i.instagram.com/api/v1/feed/tag/exampletag` but now it says "Page not found". Thanks!

**Comment by Taz03** [comment]
you can setup ssl pinning bypass to see the requests sent by your Instagram app see CONTRIBUTING.md
